version: '3.8'
services:
  example:
    image: traefik/whoami
    ports:
      - "80:80"
    env_file:
      - env.example
    deploy:
      replicas: 4
      endpoint_mode: vip
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
